# Generated by Django 5.0.7 on 2024-07-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField(blank=True, null=True)),
                ('Url', models.CharField(blank=True, max_length=255, null=True)),
                ('Content', models.CharField(blank=True, max_length=255, null=True)),
                ('Time', models.IntegerField(blank=True, null=True)),
                ('Duration', models.IntegerField(blank=True, null=True)),
                ('Expired', models.BooleanField(default=True)),
                ('StarTime', models.DateTimeField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('ExpiredAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_ads',
            },
        ),
        migrations.CreateModel(
            name='CoinFlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('server_hash', models.CharField(max_length=255)),
                ('secred_seed', models.CharField(max_length=10)),
                ('nonce', models.CharField(max_length=10)),
                ('parent_id', models.IntegerField(default=-1)),
                ('straight', models.IntegerField(default=0)),
                ('is_expired_token', models.CharField(blank=True, max_length=255, null=True)),
                ('flip_result', models.CharField(default='', max_length=5, null=True)),
                ('win', models.BooleanField(default=False)),
                ('winning_rate', models.FloatField(default=0.0)),
                ('cashout', models.FloatField(default=0.0)),
                ('bet_type', models.IntegerField(default=0)),
                ('bet_amount', models.FloatField(default=0.0)),
                ('bet_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'tbl_coinflip',
            },
        ),
        migrations.CreateModel(
            name='Cryptos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('Coinid', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'tbl_cryptos',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hash', models.CharField(blank=True, max_length=100, null=True)),
                ('RealName', models.CharField(blank=True, max_length=100, null=True)),
                ('UserName', models.CharField(blank=True, max_length=100, null=True)),
                ('UserId', models.BigIntegerField()),
                ('Wallet', models.CharField(blank=True, max_length=42, null=True)),
                ('ETH_Wagered', models.FloatField(default=0)),
                ('BNB_Wagered', models.FloatField(default=0)),
                ('TOKEN_Wagered', models.FloatField(default=0)),
                ('ETH_Wins', models.FloatField(default=0)),
                ('BNB_Wins', models.FloatField(default=0)),
                ('Token_Wins', models.FloatField(default=0)),
                ('ETH_Amount', models.FloatField(default=0)),
                ('BNB_Amount', models.FloatField(default=0)),
                ('Token_Amount', models.FloatField(default=0)),
                ('JoinDate', models.DateTimeField(auto_now_add=True)),
                ('UserAllowed', models.BooleanField(default=True)),
                ('Deployed_ETH', models.BooleanField(default=False)),
                ('ReadyTransfer', models.BooleanField(default=False)),
                ('Deployed_BNB', models.BooleanField(default=False)),
                ('Role', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tbl_users',
            },
        ),
    ]
