# Generated by Django 5.0.7 on 2024-07-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('server_hash', models.CharField(max_length=255, null=True)),
                ('secred_seed', models.CharField(max_length=10, null=True)),
                ('nonce', models.CharField(max_length=10, null=True)),
                ('flip_result', models.CharField(default='', max_length=5, null=True)),
                ('win', models.BooleanField(default=False)),
                ('cashout', models.FloatField(default=0.0)),
                ('bet_type', models.IntegerField(default=0)),
                ('bet_amount', models.FloatField(default=0.0)),
                ('bet_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'tbl_slot',
            },
        ),
    ]
